export const API_ERROR_CODES = {
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DELETING: "ACCOUNT_DELETING",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  IDEMPOTENCY_MISMATCH: "IDEMPOTENCY_MISMATCH",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  NOT_FOUND: "NOT_FOUND",
  SETUP_INCOMPLETE: "SETUP_INCOMPLETE",
  PREVIEW_CHANGED: "PREVIEW_CHANGED",
  ENTITLEMENT_REQUIRED: "ENTITLEMENT_REQUIRED",
  DOCUMENT_IMMUTABLE: "DOCUMENT_IMMUTABLE",
  APPROVAL_PENDING: "APPROVAL_PENDING",
  REQUEST_EXPIRED: "REQUEST_EXPIRED",
  REQUEST_UNAVAILABLE: "REQUEST_UNAVAILABLE",
  ALREADY_DECIDED: "ALREADY_DECIDED",
  SCOPE_CHANGED: "SCOPE_CHANGED",
  ASSET_NOT_READY: "ASSET_NOT_READY",
  ACTION_GRANT_REQUIRED: "ACTION_GRANT_REQUIRED",
  ACTION_GRANT_INVALID: "ACTION_GRANT_INVALID",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export type ApiFieldError = { field: string; message: string };

export type ApiErrorBody = {
  error: {
    code: ApiErrorCode | string;
    message: string;
    field_errors: ApiFieldError[];
    retryable: boolean;
  };
  meta: { request_id: string; server_time?: string };
};

export type ApiSuccessBody<T> = {
  data: T;
  meta: { request_id: string; server_time: string };
};

export function httpStatusForCode(code: string): number {
  switch (code) {
    case API_ERROR_CODES.AUTHENTICATION_REQUIRED:
    case API_ERROR_CODES.AUTHENTICATION_FAILED:
      return 401;
    case API_ERROR_CODES.ACCOUNT_SUSPENDED:
    case API_ERROR_CODES.ACCOUNT_DELETING:
    case API_ERROR_CODES.SETUP_INCOMPLETE:
    case API_ERROR_CODES.ACTION_GRANT_REQUIRED:
    case API_ERROR_CODES.ACTION_GRANT_INVALID:
      return 403;
    case API_ERROR_CODES.NOT_FOUND:
      return 404;
    case API_ERROR_CODES.VALIDATION_FAILED:
      return 422;
    case API_ERROR_CODES.IDEMPOTENCY_MISMATCH:
    case API_ERROR_CODES.VERSION_CONFLICT:
    case API_ERROR_CODES.PREVIEW_CHANGED:
    case API_ERROR_CODES.DOCUMENT_IMMUTABLE:
    case API_ERROR_CODES.APPROVAL_PENDING:
    case API_ERROR_CODES.REQUEST_EXPIRED:
    case API_ERROR_CODES.ALREADY_DECIDED:
    case API_ERROR_CODES.SCOPE_CHANGED:
    case API_ERROR_CODES.ASSET_NOT_READY:
      return 409;
    case API_ERROR_CODES.REQUEST_UNAVAILABLE:
      return 404;
    case API_ERROR_CODES.ENTITLEMENT_REQUIRED:
      return 403;
    case API_ERROR_CODES.RATE_LIMITED:
      return 429;
    default:
      return 500;
  }
}
