/** Quote publication snapshot schema (QUO02A). Official numbers live on documents rows. */
export const SNAPSHOT_SCHEMA_VERSION = 1;
export const FREE_JOB_LIMIT = 3;
export const PREVIEW_TTL_MS = 10 * 60 * 1000;

export {
  EMAIL_MAX_LENGTH,
  maskEmail,
  parseOwnerEmail,
  type EmailParseResult,
} from "./email.ts";
export {
  API_ERROR_CODES,
  httpStatusForCode,
  type ApiErrorBody,
  type ApiErrorCode,
  type ApiFieldError,
  type ApiSuccessBody,
} from "./envelope.ts";
export { analyticsPropertiesAreSafe, redactRecord, redactText } from "./redact.ts";
export {
  BOOTSTRAP_SUPPORT_CODES,
  EMPTY_DRAFT_SYNC,
  OFFLINE_READ_WINDOW_MS,
  OTP_LENGTH,
  OTP_MAX_FAILURES,
  RESEND_COOLDOWN_MS,
  canResend,
  isOfflineReadPermitted,
  publicRouteAllowed,
  remainingResendSeconds,
  resendAvailableAt,
  routeGroupFor,
  signOutClears,
  type AuthSnapshot,
  type AuthStatus,
  type BootstrapSupportCode,
  type DraftSyncStatus,
  type RouteGroup,
} from "./auth-state.ts";
export {
  ALL_ANALYTICS_EVENTS,
  ANALYTICS_SCHEMA_VERSION,
  CLIENT_EVENTS,
  SERVER_ONLY_EVENTS,
  isClientAnalyticsEvent,
  isServerOnlyAnalyticsEvent,
  type AnalyticsEventName,
} from "./analytics.ts";
export {
  ACTION_GRANT_ACTIONS,
  ACTION_GRANT_FRESH_AUTH_SECONDS,
  ACTION_GRANT_TTL_SECONDS,
  parseActionGrantBody,
  parseEmptyObjectBody,
  parseWithdrawBody,
  type ActionGrantAction,
} from "./action-grant.ts";
export {
  US_STATES,
  ZIP_PATTERN,
  isUsStateCode,
  parseUsAddress,
  type UsAddress,
  type UsStateCode,
} from "./address.ts";
export { parseOptionalPhone } from "./phone.ts";
export { hasDisallowedControl, parseBoundedText, parseOptionalBoundedText } from "./text.ts";
export {
  US_TIMEZONES,
  addCalendarDays,
  calendarDateInTimeZone,
  deviceTimeZone,
  endOfLocalDateUtc,
  isValidIanaTimeZone,
  naiveUtcMidnightCalendarDate,
  wallTimeToUtc,
  zonedCalendarDate,
} from "./timezone.ts";
export {
  CUSTOMER_NAME_MAX,
  FORBIDDEN_JOB_FIELDS,
  INTERNAL_NOTES_MAX,
  JOB_CREATE_FIELDS,
  JOB_LIFECYCLES,
  JOB_LIST_DEFAULT_LIMIT,
  JOB_LIST_MAX_LIMIT,
  JOB_LIST_STATES,
  JOB_MODES,
  JOB_SEARCH_MAX,
  JOB_TITLE_MAX,
  analyticsModeForJob,
  isClientUuid,
  isJobLifecycle,
  isJobListState,
  isJobMode,
  parseJobCreate,
  parseJobListQuery,
  type JobCreateInput,
  type JobCreateParseResult,
  type JobLifecycle,
  type JobListQuery,
  type JobListState,
  type JobMode,
} from "./job.ts";
export {
  CUSTOM_UNIT_LABEL_MAX,
  DRAFT_EXPIRY_DAYS_DEFAULT,
  DRAFT_LINE_FIELDS,
  DRAFT_PAYLOAD_FIELDS,
  EXPIRY_DAYS_MAX,
  EXPIRY_DAYS_MIN,
  FORBIDDEN_DRAFT_FIELDS,
  LINE_DESCRIPTION_MAX,
  LINE_UNITS,
  MAX_DRAFT_LINES,
  NOTES_MAX,
  QUANTITY_PATTERN,
  dollarsStringToCents,
  formatUsdCents,
  isLineUnit,
  parseDraftPayload,
  parseIntegerCents,
  type DraftLineInput,
  type DraftPayloadInput,
  type DraftPayloadParseResult,
  type LineUnit,
} from "./draft.ts";
export { parseQuotePublish, type QuotePublishInput, type QuotePublishParseResult } from "./quote.ts";
export {
  parseInvoiceIssue,
  parseInvoicePreview,
  type InvoiceIssueInput,
  type InvoiceIssueParseResult,
  type InvoicePreviewInput,
  type InvoicePreviewParseResult,
} from "./invoice.ts";
export {
  DUE_DAYS_MAX,
  DUE_DAYS_MIN,
  FORBIDDEN_SETUP_FIELDS,
  TAX_BP_MAX,
  TAX_BP_MIN,
  TERMS_MAX,
  WORKSPACE_SETUP_FIELDS,
  parseDueDays,
  parseTaxBp,
  parseTaxPercentToBp,
  parseWorkspaceSetup,
  taxBpToPercentLabel,
  type FieldError,
  type WorkspaceSetupInput,
  type WorkspaceSetupParseResult,
  type WorkspaceTrade,
} from "./workspace-setup.ts";

export {
  MONEY_ERROR_CODES,
  MONEY_SCHEMA_VERSION,
  type ChangeOrderInputV1,
  type ChangeOrderResultV1,
  type CreditAllocationInputV1,
  type CreditResultV1,
  type DocumentTotalsV1,
  type InvoiceCreditLineInputV1,
  type InvoiceTotalsV1,
  type LedgerStateV1,
  type LedgerViewV1,
  type LineInputV1,
  type LineResultV1,
  type MoneyErrorCode,
  type MoneySchemaVersion,
  type PaymentStatusV1,
  type ReductionResultV1,
  type ResidualInvoiceLineInputV1,
  type SourceLineInputV1,
} from "./money.ts";
