packages:
  - apps/*
  - packages/*

overrides:
  react: 19.2.3
  react-dom: 19.2.3
  react-native: 0.86.3
  typescript: 5.9.3

minimumReleaseAgeExclude:
  - zod@4.6.5
  - '@aws-sdk/client-s3@3.1132.0'
  - '@aws-sdk/s3-request-presigner@3.1132.0'

allowBuilds:
  "@embedded-postgres/darwin-arm64": true
  "@embedded-postgres/darwin-x64": true
  "@embedded-postgres/linux-arm64": true
  "@embedded-postgres/linux-x64": true
  "@embedded-postgres/windows-x64": true
